### PR TITLE
insert NCC reference for IPCC assessment process and transparency aim

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Description of PR

This PR (re)-introduces the reference to the NCC manuscript to describe the process for assessing scenarios in the IPCC SR15 context and the aim of increasing transparency and reproducibility of the assessment

### CODE REVIEW

**Comment by gidden** [comment]
what do you think of citing both?

**Comment by danielhuppmann** [comment]
that's what I did - I added the Chapter 2 reference to the link to the SR15 report page and re-inserted the NCC reference in relation to the sentence

> a scenario ensemble underpinning the quantitative assessment was compiled
 and released to facilitate transparency of the assessment and replicability of the findings in the report.

**Comment by gidden** [comment]
Ah yes, I missed it, apologies

**Comment by gidden** [comment]
Can you regenerate the pdf with a comment on Joss please?

**Pull request merged**
