### PR TITLE
updated colors, making a commit to start a PR

### LINKED ISSUE #554: IPCC AR6-RCP colors are in wrong order
The list of colors as given here [https://pyam-iamc.readthedocs.io/en/latest/tutorials/ipcc_colors.html](https://pyam-iamc.readthedocs.io/en/latest/tutorials/ipcc_colors.html) are in the wrong order, at least for the AR6-RCP color codes

ID     | name              | color
-- | -- | --
14 | AR6-RCP-2.6 | #980002
15 | AR6-RCP-4.5 | #c37900
16 | AR6-RCP-6.0 | #709fcc
17 | AR6-RCP-8.5 | #003466

and should be 
ID     | name              | color
-- | -- | --
14 | AR6-RCP-2.6 | #003466
15 | AR6-RCP-4.5 | #709fcc
16 | AR6-RCP-6.0 | #c37900
17 | AR6-RCP-8.5 | #980002

 I haven't check the other IPCC colors.

### PR DESCRIPTION
**Pull request by gidden**
# Please confirm that this PR has done the following:

- [x] Tests Added
- ~Documentation Added~
- ~Name of contributors Added to AUTHORS.rst~
- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR finalizes IPCC WG1 color pallet. 

Color values correspond to those communicated via private email by the IPCC WG1 TSU and attached here. 
[SSP WGI 2021_corrected.txt](https://github.com/IAMconsortium/pyam/files/6884897/SSP.WGI.2021_corrected.txt)

When translated to hex codes with the follow snippet

```
with open('/Users/matthewgidden/Downloads/SSP WGI 2021_corrected.txt') as f:
    for l in f.readlines()[1:]:
        line = l.strip().split()
        if not line:
            continue
        rgb = np.array([int(x) for x in l.strip().split()[1:]]) / 256
        print(l.strip().split()[0], matplotlib.colors.rgb2hex(rgb))
```

The following values come out

```
SSP1 #1e9583
SSP2 #4576be
SSP3 #f11111
SSP4 #e78731
SSP5 #8036a7
ssp119 #00a9cf
ssp126 #003466
ssp245 #f69320
ssp370 #df0000
ssp3low #e61d25
SSP43.4 #2274ae
SSP46.0 #b0724e
SSP53.4OS #92397a
ssp585 #980002
RCP2.6 #003466
RCP4.5 #709fcc
RCP6.0 #c37900
RCP8.5 #980002
```

The updated test file is attached below
test_line_PYAM_COLORS

This will close #554

### CODE REVIEW

**Comment by gidden** [comment]
FYI @danielhuppmann @znicholls @mkrapp

**Comment by gidden** [comment]
Hoping for some comments here from TSU colleagues, otherwise this is ready to merge as and when you need for the release @danielhuppmann

**Comment by gidden** [comment]
At minimum, I'd ask @znicholls to confirm colors

**Review by danielhuppmann — APPROVED** [review]
I did a spot-check against the printed figures in the SPM and it seems to be ok correct.

**Pull request merged**
