### PR TITLE
Stack plot bug part 1 issue 266

### PR DESCRIPTION
**Pull request by znicholls**
# Please confirm that this PR has done the following:

- [x] Tests Added
- [x] Documentation Added (N/A)
- [x] Description in RELEASE_NOTES.md Added

## Adding to RELEASE_NOTES.md (remove section after adding to RELEASE_NOTES.md)

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

# Description of PR

Addresses the first problem identified in #266

### CODE REVIEW

**Comment by znicholls** [comment]
This fixes the first part of #266. The wrong image can be seen [here](https://github.com/IAMconsortium/pyam/blob/ba3c0bf4a596062feafc1d94aa5c1d15ce8304b1/tests/expected_figs/test_stack_plot_missing_zero_issue_266.png) with the correction available [here](https://github.com/IAMconsortium/pyam/blob/036d48e8b6b88d1cff94d51233dadc1fe8c23764/tests/expected_figs/test_stack_plot_missing_zero_issue_266.png). Do we want this added to the tutorial too or not worry about it as this is a bug fix?

**Comment by danielhuppmann** [comment]
thanks @znicholls! I don't think that this needs to go into the tutorial, as it just fixes unexpected behaviour...

Can you rebase, then I'll merge?

**Comment by znicholls** [comment]
> Can you rebase, then I'll merge?

cool done thanks @danielhuppmann !

**Comment by danielhuppmann** [comment]
It seems that appveyor upgraded to a new version of `matplotlib`, causing this error. I think I solved a similar problem by downgrading.

@gidden, does it make sense to do that here as a quickfix, too, or is it worthwhile to make the underlying use of `matplotlib`-internals more robust?

**Comment by gidden** [comment]
Took a quick look at the logs, specifically `conda list`. 

Last success:

```
...
markupsafe                1.1.1            py37he774522_0  
matplotlib                3.0.3            py37hc8f65d3_0  
mistune                   0.8.4            py37he774522_0  
...
```

This PR:

```
...
matplotlib                3.0.3            py37hc8f65d3_0  
matplotlib-base           3.1.1            py37h2852a4a_1    conda-forge
mistune                   0.8.4            py37he774522_0
...
```

Let me do a quick test in #274

**Comment by gidden** [comment]
ok, looks like #274 has a fix. mind incorporating it?

**Comment by znicholls** [comment]
> mind incorporating it?

yep done

**Pull request merged**
