### PR TITLE
Improve performance of `pyam.concat()`

### LINKED ISSUE #500: concat uses pandas append instead of concat
The implementation of pyams concat method loops over pandas append instead of using pandas concat method. Especially for large dataframes with subannual data concat is much faster than append.

I already implemented pandas concat in pyams concat and will push it in a minute. I hope the new feature will find its way in the next release.

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

- [x] Tests Added
- [x] Documentation Added
- [x] Name of contributors Added to AUTHORS.rst
- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR refactors the implementation of `pyam.concat()` to use `pd.concat()` on the timeseries data rather than iteratively calling `IamDataFrame.append()`.

closes #500

### CODE REVIEW

**Comment by danielhuppmann** [comment]
@pjuergens, it would be great if you could try out this implementation for your use cases and report any unexpected issues. Also, it would be interesting to hear about the performance improvements in a real-world application.

**Comment by pjuergens** [comment]
@danielhuppmann thanks for working on this issue. I'll try to test the implementation today.

Concerning performance-improvement in real-world-application: We have a code in which we aggregate a lot of hourly-resolved timeseries. The bottleneck there was the pyam.append-function. Switching from append to concat on major parts of the code with my original implementation I could reduce the calculation time from 24 to 15 minutes. I'll have a deeper look at it again today when I test the new implementation.

**Comment by pjuergens** [comment]
my script ran without any issues, thanks again!

**Review by coroa — APPROVED** [review]
LGTM. I can't find any faults in that implementation. Thanks for the nice speed-up!

The next low-hanging fruit on the speed-up quest is to add a (non-copying!?) fast-path to `__init__` for a `pd.Series` in *perfect* condition, ie an index with the right names that is unique and maybe other conditions that one would have to extract from `format_data` to avoid having to reindex.

**Comment by danielhuppmann** [comment]
At some point, it will be so fast that you don't even have time for coffee while your scripts are running 😜...

**Pull request merged**
