### PR TITLE
Improved appending test for inplace behaviour

### PR DESCRIPTION
**Pull request by Rlamboll**
# Please confirm that this PR has done the following:

- [x] Tests Added
- [x] Documentation Added
- [x] Description in RELEASE_NOTES.md Added

## Adding to RELEASE_NOTES.md (remove section after adding to RELEASE_NOTES.md)

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

# Description of PR

Please describe the changes introduced by this PR.

### CODE REVIEW

**Review by danielhuppmann — COMMENTED** [review]
Thanks @Rlamboll for this improvement!

For highlighting the differences, I suggest to use pytest-parametrization:

```
@pytest.mark.parametrize("inplace", [{}, dict(inplace=True)])
def ... (test_pd_df, inplace):
    ...
       df.append(other=other, **inplace)

```

**Comment by Rlamboll** [comment]
SEVEN line changes!? Well if you insist

**Comment by danielhuppmann** [comment]
Well, I did suggest it (as a comment, not "requested changes") - but I do think that the code looks better... Thanks!

**Review by danielhuppmann — APPROVED** [review]
Thanks @Rlamboll - we can celebrate when we have reached 1000 tests! 🎉

**Pull request merged**
