### PR TITLE
Add a function to aggregate timeseries components

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

- [x] Tests Added
- [x] Documentation Added
- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR splits a "make aggregate" function out of the `check_aggregate()` function.

The PR also adapts the functions `check_aggregate()` and `check_aggregate_regions()` to be unit-specific.

For clean-up, all unit tests related to the `aggregate` features are migrated to an own file to reduce the clutter in `test_core.py`.

### CODE REVIEW

**Comment by danielhuppmann** [comment]
rebased

**Comment by danielhuppmann** [comment]
@znicholls, you implemented the function `check_aggregate_regions()` - do you have any objections to making these checks unit-specific?

**Comment by danielhuppmann** [comment]
@znicholls, seems that @gidden didn't have time any more before leaving for an extended Christmas trip to do a final review and merge - want to go ahead and squash it?

**Comment by znicholls** [comment]
nice @danielhuppmann !

**Pull request merged**
