### PR TITLE
enable compatibility with pandas v1.0

### LINKED ISSUE #311: Error using `lru_cache` on Appveyor (Windows) CI with Python 3.7
PR #310 removed testing on Appveyor with Python 3.7 as a quickfix to the problem that importing `lru_cache` fails, maybe due to https://bugs.python.org/issue36650, see also https://stackoverflow.com/questions/55834057/memoization-of-method-working-on-python-3-6-but-not-on-3-7-3

```
> pyam\iiasa.py:8: in <module>
>     from functools import lru_cache
>     ImportError: cannot import name lru_cache
```

It could be that this will be fixed when Appveyor updates to `Python > 3.7.3`, so retry in a few weeks.

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR implements a number of changes to remove any compatibility-errors with the latest release of pandas (v1.0) (as well as a minor logger-update) and regenerates the expected figures of the plotting-tests.

It also replaces `warnings.warn()` by `logger.warning()` for consistency.

closes #311

### CODE REVIEW

**Comment by gidden** [comment]
on the plotting side should be g2g. I manually tested the plots and observed no difference beyond typesetting.

**Comment by danielhuppmann** [comment]
Thanks @gidden for the effort, but color me confused...

I had already re-created the plots in  https://github.com/IAMconsortium/pyam/pull/324/commits/1c890058ccca0a2f3d71c2ce7416bde441ab04c8 and plotting tests on Appveyor passed. Now, they fail on Appveyor, but pass on Travis (where they had previously been skipped because of the issue described #327)...

Did you actually look at why Travis installs freetype 2.9.1 but then uses 2.6.1? Which version did you use to create the figures?

**Comment by danielhuppmann** [comment]
correction: the new figures from https://github.com/IAMconsortium/pyam/pull/324/commits/b343c8749d5c53b38da97ab825649f2e5c31a72c only pass on Travis with Linux, but not on Travis with Mac nor on Appveyor.

**Comment by danielhuppmann** [comment]
rebased per office discussions with @gidden, issue #327 persisting for now

**Comment by gidden** [comment]
And here we go!

**Pull request merged**
