### PR TITLE
Add list of authors to the repo and the docs

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

- [x] Documentation Added
- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR harmonizes the copyright notice and acknowledges the contribution from (non-IIASA) contributors over the past years. The logic follows the [pandas copyright model](https://github.com/pandas-dev/pandas/blob/master/AUTHORS.md). The order follows the current GitHub contributors insights (leaving out a few persons that made non-functional changes).

The PR adds a list of authors to the GitHub repo and also includes it on the docs pages. It also switches to a slightly nicer license badge on the docs page and the readme.

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Authors added (please respond if you want to have your affiliation mentioned):
@gidden, @danielhuppmann, @znicholls, @zikolach, @Rlamboll, @OFR-IIASA, @coroa, @khaeru, @tburandt, @rossursino, @mabudz, @jkikstra, @fonfon

@lumbric, I don't know your actual name, so I didn't add you... Shout if you want to be added!

**Comment by khaeru** [comment]
> please respond if you want to have your affiliation mentioned): […] @khaeru

No need for affiliation, but could you please change to "Paul Natsuo Kishimoto"? Thanks!

**Comment by danielhuppmann** [comment]
> No need for affiliation, but could you please change to "Paul Natsuo Kishimoto"? Thanks!

Sorry, @khaeru, should have thought of this...  Fixed.

**Comment by gidden** [comment]
Hi all - I will merge this PR now to allow @danielhuppmann to continue with the release schedule. please PR in a change if you have further requests on names/affiliations!

**Pull request merged**
