### PR TITLE
Fix Ip / IMP color codes for plotting

### PR DESCRIPTION
**Pull request by byersiiasa**
# Please confirm that this PR has done the following:

- [ ] Tests Added
- [ ] Documentation Added
- [x] Name of contributors Added to AUTHORS.rst
- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR fixed wrong color codes for AR6 Illustrative Pathways

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Not sure why @jkikstra added the wrong colors in #650...?

Anyway, I'll start a PR into your branch updating the test-plots so that the tests pass.

**Comment by jkikstra** [comment]
> Anyway, I'll start a PR into your branch updating the test-plots so that the tests pass.

@jkikstra also doesn't know! I assume I myself got the colours from @byersiiasa, so maybe I myself had an old version (e.g. SOD)?

**Review by jkikstra — APPROVED** [review]
I checked a few against AR6 WG3 SPM, the new colours look correct to me.

**Review by danielhuppmann — APPROVED** [review]
Thanks @byersiiasa & @jkikstra!

**Pull request merged**
