### PR TITLE
add function to normalize

### PR DESCRIPTION
**Pull request by gidden**
starting to add a function to normalize all data to a specific time value

### CODE REVIEW

**Comment by gidden** [comment]
we can probably rework this to normalize to any specific subset of data, just works for time at the moment

**Comment by gidden** [comment]
Ok @danielhuppmann all suggested changes made!

**Comment by danielhuppmann** [comment]
thanks @gidden, looks great! do you want to add it to the release notes for completeness?

**Comment by gidden** [comment]
done!

**Pull request merged**
