### PR TITLE
add a function `compare()` to compare two IamDataFrames

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

- [x] Tests Added
- [x] Documentation Added
- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR introduces a function `compare()` to compare the `data` tables of two IamDataFrames using the `np.isclose()` function.

### CODE REVIEW

**Comment by gidden** [comment]
lgtm, one suggestion though: should we add an additional option(s)? Specifically, I'm thinking difference, relative difference, and anything else? so you would see the difference in the test is `(2 - 1) = 1` and `(2 - 1) / 2 = 0.5`?

**Comment by danielhuppmann** [comment]
The comparison is using `np.isclose()` and you can pass the kwargs to it through the `compare()` function. So absolute and relative tolerance can be specified, though you have to keep in mind that `np.isclose()` is not symmetric, so `np.isclose(a, b)` does not necessary equal `np.isclose(b, a)`. Still, this is good enough for my use case...

@gidden, can you specify a use case that requires a more elaborate treatment?

**Comment by gidden** [comment]
I see that `np.isclose` is used. I was suggesting two separate things I suppose:

1. the definition of close could be in absolute magnitude or relative (within 50%, for example)
2. it is likely useful to see what the difference is, thus adding a column which provides `a - b` in addition to `a` and `b`

Another thought is this API/feel is close to looking like [`pd.subtract`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.subtract.html) and could be confused with `pd.diff`.

Perhaps we should take the pandas route and supply a `subtract` function. Then we could make a `compare` function which houses what you describe here. One possible function signature could be:

```
pyam.compare(left, right, left_label='left', right_label='right', kind='diff', drop_close=True, **kwargs)
```

**Comment by danielhuppmann** [comment]
rebased to resolve merge conflicts

**Comment by danielhuppmann** [comment]
I see the point of broader `compare()` function (not so sure that subtracting makes sense or that it can be confused with  'first-difference' as in `pd.diff()`).

Anyway, I refactored to `compare()` and added `drop_close` as a kwarg. Other kwargs such as `kind` (or maybe `method`?) can be added at a later point.

**Comment by danielhuppmann** [comment]
Another idea for a use case of this function (jotted down here for future reference):

`pyam.compare(df, on={'scenario': ('scenario_a', 'scenario_b')})`

which would show the difference between two scenarios with different names within on IamDataFrame (whereas the current implementation compares scenarios with the same name across two IamDataFrames).

**Comment by gidden** [comment]
Awesome, thanks!

**Pull request merged**
