### PR TITLE
Improve performance of IamDataFrame initialization (phase 2)

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

- ~Tests Added~
- ~Documentation Added~
- ~Name of contributors Added to AUTHORS.rst~
- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR is a follow-up to #579, implementing further performance improvements.

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Summarizing bilateral discussions with (and manual benchmarking done by) @phackstock - this PR shows again some improvements in memory usage. One interesting observation is that the initial commit here https://github.com/danielhuppmann/pyam/commit/d652297fc39c9176be661bb508d97d42d02b795b, which uses `df.set_index(.., append=True)` performs much *worse* than either the previous implementation or the "manual" adding-to-index using the pyam.index module...

**Comment by danielhuppmann** [comment]
Running benchmarking with **pytest-monitor** and **memory-profiler** on the IAMC 1.5°C scenario ensemble data for all regions (~80MB, xlsx) shows that this PR increases time use by ~20%, but reduces memory use by 30%... Not quite sure if that is a worthwhile trade-off, or if it can be improved...

**Comment by phackstock** [comment]
Regarding your question @danielhuppmann my vote would be in favor of saving memory even if the price for that is a longer execution time. 
My reasoning is that a longer execution time means more waiting for the user while memory savings can decide whether or not a user might be able to open a data set at all. 
Ideally, if you're working in a jupyter notebook you read the data only once and keep it in memory anyway so I don't think that a plus in execution time is that big of a deal.

**Comment by danielhuppmann** [comment]
closing in favor of #729 and #730

**Pull request closed without merging**
