### PR TITLE
Enable explicit `label` and fix for non-string items in plot legend

### LINKED ISSUE #518: plot and line_plot fail with label arguments
Following the most recent update, line_plot, and the new preferred function plot, both now fail when used with "label" arguments, or if used without "color" arguments under very simple circumstances. Minimal coding example: 

import pyam
import pandas as pd
# Define dataframe:
_mc = "model_c"
_sa = "scen_a"
_sb = "scen_b"
_eco2 = "Emissions|CO2"
_gtc = "Gt C/yr"
_ech4 = "Emissions|CH4"
_mtch4 = "Mt CH4/yr"
_msrvu = ["model", "scenario", "region", "variable", "unit"]
simple_df = pd.DataFrame(
    [
        [_mc, 1, "World", _eco2, _gtc, 0, 1000, 5000],
        [_mc, _sb, "World", _eco2, _gtc, 1, 1000, 5000],
        [_mc, _sa, "World", _ech4, _mtch4, 0, 300, 500],
        [_mc, _sb, "World", _ech4, _mtch4, 1, 300, 500],
    ],
    columns=_msrvu + [2010, 2030, 2050],
)
simple_df = pyam.IamDataFrame(simple_df)
# The following fails:
simple_df.filter(variable=_eco2).plot()
# The following works: 
simple_df.filter(variable=_eco2).plot(color='scenario')
# The following both fail: 
simple_df.filter(variable=_eco2).plot(color='scenario', label="sillyString")
simple_df.filter(variable=_eco2).plot(color='scenario', label=["sillyString"])

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

Not applicable as this is only a minor bugfix

- [x] Tests Added
- ~Documentation Added~
- ~Name of contributors Added to AUTHORS.rst~
- [x] Description in RELEASE_NOTES.md Added

# Description of PR

This PR enables an explicit `label` kwarg to be passed to `IamDataFrame.plot.line()` and fixes an error when creating a line-plot legend where the columns are not strings.

closes #518

### CODE REVIEW

**Comment by Rlamboll** [comment]
The code change seems satisfactory, but do we not want to test that this function works? At least that requesting a plot with and without a label argument produces a plot of some kind, even if testing what the legend actually says is rather annoying?

**Comment by danielhuppmann** [comment]
Added two tests for the explicit-label feature for line plots, but tests are currently failing due to the WorldBank data API...

**Review by Rlamboll — APPROVED** [review]
Great work! Hopefully the world bank databases will work soon.

**Comment by danielhuppmann** [comment]
Worldbank database is up again, all tests pass

**Pull request merged**
