### PR TITLE
Add ability to request regions with synonyms from IXMP web API

### PR DESCRIPTION
**Pull request by zikolach**
Changes
- (optionally) fetch region synonyms
- fix fetching timeseries data explicitly specifying column types

---
- [x] Tests Added
- [x] Documentation Added
- [x] Description in RELEASE_NOTES.md Added

### CODE REVIEW

**Comment by byersiiasa** [comment]
lgtm

**Comment by gidden** [comment]
Haven't had a chance to review implementation, but we need at least one functionality test

**Comment by zikolach** [comment]
@gidden @danielhuppmann I added a test (as backend used for integration testing is now up-to-date). Can you please re-review?

**Comment by danielhuppmann** [comment]
thanks @zikolach - I was hoping that @gidden or @byersiiasa would review this, because I'm not sure how this is supposed to work...

Can you please rebase to resolve the merge conflict (changed `logger` implementation in #288)?

More generally, I'm not sure if this return-object (in wide format) is helpful, because one would need to check across an unknown number of columns (if I understand the format with `synonym_{}` correctly?). I think a return-object in long-format (see https://github.com/iiasa/ixmp/blob/399e1b04db32b8fb6f090dba611a900fd4c421ea/ixmp/core.py#L219) would be more practical?

Also, we should be able to tag "types" to synonyms, to distinguish between standard name, ISO3, alternative spelling, ...

**Comment by zikolach** [comment]
PR rebased

> More generally, I'm not sure if this return-object (in wide format) is helpful, because one would need to check across an unknown number of columns (if I understand the format with synonym_{} correctly?). I think a return-object in long-format (see https://github.com/iiasa/ixmp/blob/399e1b04db32b8fb6f090dba611a900fd4c421ea/ixmp/core.py#L219) would be more practical?

The intention was to keep it kind of backward-compatible (meaning regions method should return same (unique) list of regions). What do you think about adding/extending method parameters, e.g. instead of `include_synonyms` have `synonyms_format` with:
- default option (None) to omit synonyms
- option `columns` - current behavior
- option `rows` - long format

> Also, we should be able to tag "types" to synonyms, to distinguish between standard name, ISO3, alternative spelling, ...

Can you explain a bit more in detail what you mean? Dtypes? What is recommended way to do it?

**Comment by danielhuppmann** [comment]
Thanks @zikolach!

For backward compatibility, `include_synonyms=False` can be used as default.

I don't see a practical use case for `columns` format, because an a-priori unknown number of meaningful entries would make it a bit tedious working with a wide format. So just return `rows` (long format) for `include_synonyms=True`.

> > Also, we should be able to tag "types" to synonyms, to distinguish between standard name, ISO3, alternative spelling, ...

> Can you explain a bit more in detail what you mean? Dtypes? What is recommended way to do it?

Ignore this comment, let's tackle this at some future point - I realised this opens quite a few rabbit holes.

**Comment by zikolach** [comment]
> I don't see a practical use case for columns format, ...

Practical use case is to get first synonym for specific region. With long format it is a bit more difficult (as I can see from my limited pandas knowledge)

**Comment by danielhuppmann** [comment]
There is no such thing as a “first”, “second”, etc. synonym in the current logic. There can be any number of them, in any order.

We may want to introduce tags for synonyms, e.g. the ISO3 synonym (what I meant earlier). But this would require a major change in ixmp, restAPI, etc., so not to be tackled now.

**Comment by zikolach** [comment]
> There is no such thing as a “first”, “second”, etc.

I meant "first available synonym", but that is not important. Main constraint as mentioned was to keep region names unique in the result dataset independently on parameters. If that is no issue then it is ok from my side also to implement as you suggested. Please re-review changes.

**Pull request merged**
