### PR TITLE
remove all region-plotting related features, docs, etc.

### PR DESCRIPTION
**Pull request by gidden**
This completely removes all region-plotting related code. I will make an issue to reinstate it.

### CODE REVIEW

**Comment by znicholls** [comment]
What's the motivation for removing `map_regions`, that works fine doesn't it?

**Comment by danielhuppmann** [comment]
> What's the motivation for removing `map_regions`, that works fine doesn't it?

See the related issue https://github.com/IAMconsortium/pyam/issues/225

**Comment by znicholls** [comment]
> See the related issue #225

Ok but there's features in `map_region` that aren't in `aggregate_region` right? Particularly the inbuilt mappings? If this is a refactoring operation (which is my understanding of #225), wouldn't it make sense to leave `map_regions` in and ensure continuity of the tests during the refactoring? (I ask out of curiosity and to learn more about how to approach this sort of operation, I don't actually have any strong feelings.)

**Comment by gidden** [comment]
Ok all, thanks first to @znicholls - we can and should keep `map_region` in for the moment. It's added back with tests, this should be good to go now.

**Pull request merged**
