### PR TITLE
Make default logging more verbose

### LINKED ISSUE #293: no logging output in Jupyter notebooks
Following the merge of #288, there is no logging output written in Jupyter notebooks or ipython!

Is this a feature or a bug? (If it's a feature, it's not a great one).

### PR DESCRIPTION
**Pull request by znicholls**
# Please confirm that this PR has done the following:

- [ ] Tests Added
- [ ] Documentation Added
- [ ] Description in RELEASE_NOTES.md Added

## Adding to RELEASE_NOTES.md (remove section after adding to RELEASE_NOTES.md)

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

# Description of PR

Closes #293

### CODE REVIEW

**Comment by danielhuppmann** [comment]
thanks @znicholls, this is more in line with what I'd expect in practice, logging-wise...

Logging output is now written in Jupyter notebooks and ipython consoles, but not a python console. It's not clear to me why one would not want to always display `INFO` output per default.

**Comment by danielhuppmann** [comment]
@zikolach, can you please check whether the (already merged) change in #288 and/or this PR will affect (or break) the log output for the "upload to IIASA database" workflow?

**Comment by znicholls** [comment]
> It's not clear to me why one would not want to always display `INFO` output per default.

It's just the community standard, by default only WARNING and above will appear. If you want INFO, you have to turn it on yourself (by namespacing your logger you let users of your library decide what they see and don't see rather than deciding for them). 

> @zikolach, can you please check whether the (already merged) change in #288 and/or this PR will affect (or break) the log output for the "upload to IIASA database" workflow?

If you're relying on getting INFO level log output, the answer is almost certainly yes.

**Comment by danielhuppmann** [comment]
Ok, colour me ignorant, but I still think that it makes sense to be more verbose in Jupyter notebooks per default...

So I'm happy with this PR - unless @gidden or @zikolach have objections, I'd say it's ready to be merged...

**Comment by znicholls** [comment]
> Ok, colour me ignorant, but I still think that it makes sense to be more verbose in Jupyter notebooks per default...

We can make pyam more verbose in the console too if we want. I think as long as there's a message that lets users know what's happening, they can turn things off later if they want and it might be the right choice for pyam users.

**Comment by danielhuppmann** [comment]
> We can make pyam more verbose in the console too if we want.

I don't have a preference about the default logging level in the console. @gidden, if you don't have a strong opinion here, I'll merge as is to get the notebook logging fixed.

**Comment by danielhuppmann** [comment]
merging as is to fix Jupyter notebook logging

please make an issue to restart the discussion whether the default logging level should be `INFO` in the console for consistency

**Pull request merged**
