### PR TITLE
Df load meta

### PR DESCRIPTION
**Pull request by gidden**
# Please confirm that this PR has done the following:

- ~[ ] Tests Added~ - existing tests cover use case
- [x] Documentation Added
- [x] Name of contributors Added to AUTHORS.rst
- [x] Description in RELEASE_NOTES.md Added

## Adding to RELEASE_NOTES.md (remove section after adding to RELEASE_NOTES.md)

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

# Description of PR

This PR implements support for setting metadata by dataframes, and implements all metadata setting solely via `set_meta()`

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Thanks @gidden! One side effect of your clean-up is that the warnings are no longer shown if the (timeseries) `data` sheet and the `meta` of a file are inconsistent. Given that we are starting to use the meta-indicators-feature that more in the scenario-submission workflows, I'd be very much in favor of keeping the warnings.

**Comment by gidden** [comment]
Changes to `load_meta()` reverted!

**Review by danielhuppmann — APPROVED** [review]
Thanks @gidden, lgtm!

**Comment by gidden** [comment]
@danielhuppmann - only style changes, should be g2g

**Comment by gidden** [comment]
With lgtm above and passing tests, merging

**Pull request merged**
