### PR TITLE
Deliberately exclude pandas 0.24.0 and update dev environment creation instructions

### PR DESCRIPTION
**Pull request by znicholls**
# Please confirm that this PR has done the following:

- [x] Tests Added (N/A)
- [x] Documentation Added (N/A)
- [x] Description in RELEASE_NOTES.md Added

## Adding to RELEASE_NOTES.md (remove section after adding to RELEASE_NOTES.md)

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

# Description of PR

Deliberately excludes Pandas 0.24.0 from compatible versions due to a bug (bug was fixed in 0.24.1)

### CODE REVIEW

**Comment by znicholls** [comment]
quick one just to make dependencies clearer for users

**Comment by gidden** [comment]
should we also add here `geopandas<0.5.0` for the moment?

**Comment by gidden** [comment]
Hey @znicholls, is this good to go for inclusion in `0.2.0`?

**Comment by znicholls** [comment]
It is now :)

**Comment by gidden** [comment]
looks great, thanks @znicholls !

**Pull request merged**
